server:
  port: 8888

spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          basedir: ./config-repo
          default-label: main
